added battery percentage and state
technojam/AndroidCustomView pull request #16
Opened 2020-10-03 17:30 UTC by rishab2890

2020-10-03 17:42 UTC, noman2002 commented
hey, @rishab2890  Add discription to it. Attach screenshot .

2020-10-03 18:10 UTC, Areeb786123 requested changes
U have implement only charging  and its percentage without canvas and also Implement scrollView .

2020-10-04 08:07 UTC, danishjamal104 requested changes
@rishab2890 please look into all the comments and make necessary changes.

2020-10-04 08:07 UTC, danishjamal104 commented on README.md
> +<img src="screenshots/Screenshot_1601744805.png">
replace the existing screenshot without changing the file name.

2020-10-04 08:07 UTC, danishjamal104 commented on app/src/main/res/layout/activity_main.xml
> +    <TextView
You have to implement a custom view. Don't use predefined tags like textView or anything define your own View class BatteryView or something.

2020-10-04 08:07 UTC, danishjamal104 commented on app/src/main/res/layout/activity_main.xml
>          android:strokeColor="@color/colorPrimary"
If you are making any changes or removing any attribute then specify it in the description.

2020-10-04 08:07 UTC, danishjamal104 commented on app/src/main/res/layout/activity_main.xml
> +
Please avoid adding an extra line in files.
Also, try to remove EOF.

2020-10-06 06:45 UTC, noman2002 requested changes
Make changes as suggested by @danishjamal104

2020-10-08 20:32 UTC, noman2002 commented
@rishab2890 please be active on the PR until it is open, else I have to close this PR.

2020-10-10 06:50 UTC, closed without merging